#!/usr/bin/env bash
#Displays a list of currently running processes
#
must show all processes , for all users, including those which might not have TTY
#Display in a user-oriented format
#Show process hierachy
ps -auxf
