#!/usr/bin/env bash
# that displays numbers from 1 to 100, FizzBuzz multiple of 3 and 5, Fizz multiple of 3 and Buzz multiple of 5. 

for i in {1..100}
do
	if (( i % 15 == 0))	
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0))
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
