#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
#
#   - Display hours from 0 to 12
#   - Display minutes from 1 to 59

h=0
while [ $h != 13 ];
do
	min=1
	echo "Hour: $h"
	while [ $min != 60 ];
	do
		echo $min
		((min++))
		
	done
	((h++))
done
